from __future__ import annotations

import random
from dataclasses import dataclass, replace
from datetime import datetime
from pathlib import Path
from typing import Any, Sequence

from agent_office.backtest import RuleBaselineBacktester, result_summary
from agent_office.config import AppConfig, StrategyParams
from agent_office.models import Candle


@dataclass(frozen=True)
class CandidateParams:
    stop_atr_multiple: float
    min_stop_distance_pct: float
    max_concurrent_positions: int


@dataclass(frozen=True)
class EvaluatedCandidate:
    params: CandidateParams
    train: dict[str, Any]
    validate: dict[str, Any]
    test: dict[str, Any] | None
    score: float


def optimize_strategy_params(
    config: AppConfig,
    candles_4h_by_symbol: dict[str, Sequence[Candle]],
    candles_1d_by_symbol: dict[str, Sequence[Candle]],
    train_start: datetime,
    train_end: datetime,
    validate_start: datetime,
    validate_end: datetime,
    test_start: datetime | None = None,
    test_end: datetime | None = None,
    samples: int = 20,
    seed: int = 7,
    min_trades: int = 20,
) -> dict[str, Any]:
    if samples <= 0:
        raise ValueError("samples must be positive")
    if train_end <= train_start or validate_end <= validate_start:
        raise ValueError("invalid train/validate date range")
    if (test_start is None) != (test_end is None):
        raise ValueError("test_start and test_end must be provided together")
    if test_start is not None and test_end is not None and test_end <= test_start:
        raise ValueError("invalid test date range")

    rng = random.Random(seed)
    candidates = [_current_params(config)]
    candidates.extend(_sample_params(rng) for _ in range(samples))

    evaluated: list[EvaluatedCandidate] = []
    for params in candidates:
        candidate_config = _config_with_params(config, params)
        train = _run_summary(candidate_config, candles_4h_by_symbol, candles_1d_by_symbol, train_start, train_end)
        validate = _run_summary(candidate_config, candles_4h_by_symbol, candles_1d_by_symbol, validate_start, validate_end)
        score = _score(validate, min_trades=min_trades)
        evaluated.append(EvaluatedCandidate(params=params, train=train, validate=validate, test=None, score=score))

    evaluated.sort(key=lambda item: (item.score, item.validate["net_pnl_usdt"], item.validate["profit_factor"] or 0), reverse=True)
    best = evaluated[0]
    test = None
    if test_start is not None and test_end is not None:
        candidate_config = _config_with_params(config, best.params)
        test = _run_summary(candidate_config, candles_4h_by_symbol, candles_1d_by_symbol, test_start, test_end)
        best = EvaluatedCandidate(params=best.params, train=best.train, validate=best.validate, test=test, score=best.score)

    return {
        "seed": seed,
        "samples": samples,
        "min_trades": min_trades,
        "best": _candidate_payload(best),
        "top_candidates": [_candidate_payload(item) for item in evaluated[: min(10, len(evaluated))]],
    }


def tuned_config_toml(config: AppConfig, params: CandidateParams) -> str:
    symbols = "\n".join(f'  "{symbol}",' for symbol in config.watchlist)
    return f'''# ML-style tuned config generated by agent-office optimize.

trading_mode = "{config.trading_mode.value}"
watchlist = [
{symbols}
]

db_path = "{config.db_path.as_posix()}"
starting_equity_usdt = {config.starting_equity_usdt:.2f}
default_leverage = {config.default_leverage:.2f}

[risk_limits]
max_risk_per_trade_pct = {config.risk_limits.max_risk_per_trade_pct}
max_leverage = {config.risk_limits.max_leverage}
max_concurrent_positions = {params.max_concurrent_positions}
max_total_notional_to_equity = {config.risk_limits.max_total_notional_to_equity}
daily_loss_limit_pct = {config.risk_limits.daily_loss_limit_pct}
max_drawdown_pct = {config.risk_limits.max_drawdown_pct}

[strategy]
stop_atr_multiple = {params.stop_atr_multiple}
min_stop_distance_pct = {params.min_stop_distance_pct}
'''


def _current_params(config: AppConfig) -> CandidateParams:
    return CandidateParams(
        stop_atr_multiple=config.strategy.stop_atr_multiple,
        min_stop_distance_pct=config.strategy.min_stop_distance_pct,
        max_concurrent_positions=config.risk_limits.max_concurrent_positions,
    )


def _sample_params(rng: random.Random) -> CandidateParams:
    atr_choices = [1.0, 1.25, 1.5, 2.0, 2.5, 3.0, 3.5]
    stop_choices = [0.005, 0.0075, 0.01, 0.015, 0.02]
    position_choices = [1, 2, 3]
    return CandidateParams(
        stop_atr_multiple=rng.choice(atr_choices),
        min_stop_distance_pct=rng.choice(stop_choices),
        max_concurrent_positions=rng.choice(position_choices),
    )


def _config_with_params(config: AppConfig, params: CandidateParams) -> AppConfig:
    risk_limits = replace(config.risk_limits, max_concurrent_positions=params.max_concurrent_positions)
    strategy = StrategyParams(
        stop_atr_multiple=params.stop_atr_multiple,
        min_stop_distance_pct=params.min_stop_distance_pct,
    )
    return replace(config, risk_limits=risk_limits, strategy=strategy)


def _run_summary(
    config: AppConfig,
    candles_4h_by_symbol: dict[str, Sequence[Candle]],
    candles_1d_by_symbol: dict[str, Sequence[Candle]],
    start: datetime,
    end: datetime,
) -> dict[str, Any]:
    result = RuleBaselineBacktester(config).run(candles_4h_by_symbol, candles_1d_by_symbol, start, end)
    return result_summary(result, trade_limit=0)


def _score(summary: dict[str, Any], min_trades: int) -> float:
    net = float(summary["net_pnl_usdt"])
    drawdown = float(summary["max_drawdown_pct"])
    trades = int(summary["trades"])
    profit_factor = float(summary["profit_factor"] or 0)
    trade_penalty = max(0, min_trades - trades) * 50
    pf_penalty = max(0.0, 1.0 - profit_factor) * 500
    return round(net - (drawdown * 50) - trade_penalty - pf_penalty, 2)


def _candidate_payload(candidate: EvaluatedCandidate) -> dict[str, Any]:
    payload = {
        "params": {
            "stop_atr_multiple": candidate.params.stop_atr_multiple,
            "min_stop_distance_pct": candidate.params.min_stop_distance_pct,
            "max_concurrent_positions": candidate.params.max_concurrent_positions,
        },
        "score": candidate.score,
        "train": _compact_summary(candidate.train),
        "validate": _compact_summary(candidate.validate),
    }
    if candidate.test is not None:
        payload["test"] = _compact_summary(candidate.test)
    return payload


def _compact_summary(summary: dict[str, Any]) -> dict[str, Any]:
    return {
        "net_pnl_usdt": summary["net_pnl_usdt"],
        "return_pct": summary["return_pct"],
        "max_drawdown_pct": summary["max_drawdown_pct"],
        "trades": summary["trades"],
        "win_rate_pct": summary["win_rate_pct"],
        "profit_factor": summary["profit_factor"],
    }